### ISSUE TITLE
pg2 scheduled for removal

### ISSUE THREAD

**Issue by savtrip** [koudelka/honeydew#110]
Hey @koudelka,

I noticed you use pg2 within honeydew. Advanced notice that Erlang will remove the pg2 API in favour of the pg API for OTP 24. 

Sources:
- https://erlang.org/doc/man/pg2.html
- https://www.erlang.org/news/140

**Comment by koudelka** [comment]
thanks for the heads up!

**Comment by zeeshanlakhani** [comment]
@koudelka using honeydew now as well (at @blockfi). Would love to see this change/update.

**Comment by zeeshanlakhani** [comment]
I have some thoughts on how it may work w/ the reintroduced `pg`, but figure you may have an idea already.

**Comment by simoncocking** [comment]
With the release of OTP 24 and Elixir 1.12, we're effectively blocked from upgrading by our use of Honeydew. Is there an ETA for the update to use `pg` over `pg2`?

**Comment by koudelka** [comment]
Hey hey, the OTP 24 release is on master right now, would you mind giving it a whirl and letting me know how it goes? I'll cut a hex release if it looks all good. :)

**Comment by icehaunter** [comment]
@koudelka works for us on master!

**Comment by koudelka** [comment]
just published `1.5.0` to hex, 1.12.0 + OTP 24 are the minimum versions going forward. 

holler if there are any issues and i'll push point fixes! :)

**Comment by simoncocking** [comment]
Sorry for the delayed reply - so far, `1.5.0` looks good here! Thanks for the swift response!

**Comment by zeeshanlakhani** [comment]
guessing we can close this @koudelka? :)

**Comment by koudelka** [comment]
ah, yep! :)
