### ISSUE TITLE
How to cancel Jobs in Ecto Queue?

### ISSUE THREAD

**Issue by mohandass-pat** [koudelka/honeydew#111]
Hi,
 Right now We are implementing honeydew jobs using ecto queue. We cannot able to find the right function to cancel jobs in ecto queue. There are functions to cancel Mnesia and erlang queue jobs. But now function is available on Ecto Queue. Can you Share an example function to cancel ecto jobs.

**Comment by koudelka** [comment]
Hey @mohandass-pat,

Check out the Ecto queue example tests:

https://github.com/koudelka/honeydew/blob/master/examples/ecto_poll_queue/test/ecto_poll_queue_example_test.exs#L86

Keep in mind that once a job is being run by a worker, there's no way to forcefully kill it at present. This function simply removes the job from the queue.
