### ISSUE TITLE
Shutdown hangs

### ISSUE THREAD

**Issue by martinos** [koudelka/honeydew#126]
When I shutdown my app the application hangs (when I send a SIGTERM). I noticed the following log message:

```
﻿2023-02-22 14:26:42.969 [info]     :alarm_handler: {:clear, :system_memory_high_watermark}
2023-02-22 14:26:42.972 [warn] [Honeydew] Worker "my_worker" (#PID<0.7756.1>) saw its job runner (#PID<0.7834.1>) die (reason shutdown) during a job, restarting...
```
I don't know if this is related but it seems that it's the case.

**Comment by martinos** [comment]
```
      Honeydew.start_workers(queue_name, My.Worker,
        num: 4,
        shutdown: 30_000
      )
```

**Comment by koudelka** [comment]
can you create a minimal reproduction?

**Comment by martinos** [comment]
I am trying to reproduce it. For the time being, do you think that it might be related to the log that says:

```
Worker "my_worker" (#PID<0.7756.1>) saw its job runner (#PID<0.7834.1>) die (reason shutdown) during a job, restarting...
```
Because if the Worker tries to restart the job, it might just loop forever. However I would say that I am doing Elixir on and off so I might be wrong. 


Or maybe the log is wrong in this case?

**Comment by koudelka** [comment]
it's totally possible that it's related, you might try modifying your `shutdown` argument to see if that changes the amount of time it hangs

**Comment by martinos** [comment]
Thanks, I will try this.

**Comment by martinos** [comment]
I tried to change the production timeout to half (15_000 instead of 30_000, and I still have the issue. I've waited for more than 2hrs for shutdown, and the application was still hanged. 

I don't have this error in every case: 

```
saw its job runner (#PID<0.7834.1>) die (reason shutdown) during a job, restarting...
```

Thus it might not be related. 

But this one seems common to all hangs:

```
2023-02-27 13:40:52.031 [error] GenServer #PID<0.3881.0> terminating
** (stop) {:aborted, {:node_not_running, :my_app@my_node}}
    (mnesia 4.19) mnesia_tm.erl:753: :mnesia_tm.non_transaction/5
    (honeydew 1.4.5) lib/honeydew/queue.ex:358: Honeydew.Queue.dispatch/1
    (honeydew 1.4.5) lib/honeydew/queue/mnesia.ex:346: Honeydew.Queue.Mnesia.handle_info/2
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: :__poll__
State: %Honeydew.Queue.State{dispatcher: {Honeydew.Dispatcher.LRU, {{[#PID<0.3894.0>, #PID<0.3893.0>, #PID<0.3892.0>], [#PID<0.3891.0>]}, #MapSet<[]>}}, failure_mode: {Honeydew.FailureMode.ExponentialRetry, [times: 12, base: 2, finally: {Honeydew.FailureMode.Move, [queue: :timeouts]}]}, job_monitors: %{}, module: Honeydew.Queue.Mnesia, private: %Honeydew.Queue.Mnesia.PState{access_context: :async_dirty, in_progress_table: :"honeydew_\"redacted\"_in_progress", table: :"honeydew_\"redacted\""}, queue: "redacted", success_mode: nil, suspended: false}

```

**Comment by koudelka** [comment]
have you tried opening an iex shell on your production box and looking at what's cookin'? (what supervision trees haven't shut down? what processes are getting spawned? etc…)

**Comment by martinos** [comment]
I should have told you before, when I try to connect to the app , iex does not respond. I am a bit confused. 

```
$>  ./my_app  remote
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]


```
It hangs, 

And if look at the pid the process is still there. 

```
$ ./my_app pid
31849
$ ps aux | grep 31849
prod      6552  0.0  0.0 112724  2456 pts/2    S+   15:24   0:00 grep --color=auto 31849
prod     31849  0.2  2.5 2314244 102960 ?      Sl   13:39   0:15 /opt/apps/my_app/erts-11.2/bin/beam.smp -C multi_time_warp -- -root /opt/apps/my_app -progname erl -- -home /home/prod -- -noshell -s elixir start_cli -mode embedded -setcookie AG4UV5QTHQJOV5UYKEJ5I33ZLCTLMKH7DBV2NG5BMOXME4X75FWQ==== -sname my_app -config /opt/apps/my_app/releases/0.1.0/sys -boot /opt/apps/my_app/releases/0.1.0/start -boot_var RELEASE_LIB /opt/apps/my_app/lib -- -- -extra --no-halt
```

The erlang process seems to be there.

**Comment by koudelka** [comment]
hm, i'd guess that processes necessary for console access have already shut down.

are you able to interrogate the node via `:rpc` from another node in the cluster?

you might try starting an unsupervised and unlinked process on your prod nodes that dumps the supervision trees and associated information to disk on an interval, that way when a node exhibits this behaviour, you can just go check the latest dump to see what's running.

**Comment by martinos** [comment]
I think my problem comes from the fact that neither the queues or  the workers are under my app supervisor. Thus when they shutdown they can refer to mnesia that has been shutdown . 

Here's my application mix function.

```
  def application do
    [
      mod: {MyApp.Application, []},
      extra_applications: [:logger, :runtime_tools, :os_mon],
      included_applications: [:mnesia]
    ]
  end
```

I am wondering if mnesia is in Honeydew application supervisor? 

Also, my workers depends on Ecto, so they should be shutdown before Ecto.
 
How should I build my app supervisor? My workers are running on the same node that the queues.

**Comment by martinos** [comment]
I have added `:honeydew` in the `:included_applications` and  added `Honeydew.Workers` and `Honeydew.Queues` in my application supervisor. I have also moved  `:mnesia` from my `:included_application` section to `:extra_applications` and everything seems to work fine now.

Thus I think that in the case that Honeydew takes care of starting `:mnesia`, it can cause shutdown issues.
