### ISSUE TITLE
Unexpected behavior when forgetting to define init/1

### ISSUE THREAD

**Issue by aaronrenner** [koudelka/honeydew#13]
I just had a difficult to troubleshoot issue when I accidentally defined `init/0` instead of `init/1`.  My worker module looked like this.

```elixir
defmodule MyWorker do
  def init do: {:ok, nil}

  def run(arg, _state) do
   # do work
  end
end
```
I had my queues set up properly and the following log messages were printed when my app started up so I assumed everything started correctly.
```
10:32:36.283 [debug] [Honeydew] Worker #PID<0.268.0> sending ready

10:32:36.283 [debug] [Honeydew] Worker #PID<0.267.0> sending ready

10:32:36.283 [debug] [Honeydew] Queue #PID<0.264.0> ready for worker #PID<0.267.0>

10:32:36.283 [debug] [Honeydew] Queue #PID<0.264.0> ready for worker #PID<0.268.0>
```

However when I tried to call the function using honeydew
```elixir
{:run, ["hello"]} |> Honeydew.async(:my_queue)
```
I would get the following error:
```
10:31:28.429 [error] GenServer #PID<0.745.0> terminating
** (UndefinedFunctionError) function MyWorker.run/1 is undefined or private. Did you mean one of:

      * run/2
```
It wasn't until I put an IO.inspect in my `init/0` function that I found it wasn't being called because it should have been `init/1`.

Ideally, it would be nice to either raise an exception if an `init/1` function wasn't defined on a worker, or document that you could skip defining an `init/1` function but then it won't pass the last state argument into the functions you call on the worker.

**Comment by koudelka** [comment]
documented in https://github.com/koudelka/honeydew/blob/master/examples/initialized_worker/README.md now
