### ISSUE TITLE
Jobs are not restarted on node "crash"

### ISSUE THREAD

**Issue by samphilipd** [koudelka/honeydew#22]
Not sure if this is something the library doesn't support, or if I have missed something.

I am trying to have the node automatically retry jobs that were running on a node that died. I'm using mnesia storage.

I boot a node and start a bunch of long running jobs, then ctrl-c the iex session.

I boot a new node with the same name. I can see all the jobs I just started using `Honeydew.status(:my_queue)` but they just show as `in_progress` forever.

Is there a way to have those automatically retried by the new node?

**Comment by koudelka** [comment]
Hey @samphilipd, that's a completely legitimate bug, thanks for the report!

Fixed in 4810f6c0c275fe0881a4c911016f39857027aa2e and published version `1.0.2`.

Please let me know how it works out. :)

**Comment by samphilipd** [comment]
@koudelka Wicked! Will this work in both local and `:global` modes?

**Comment by koudelka** [comment]
Yep yep, the only caveat is that a crashed queue process must restart on a node with the same name. (Basically, just restart the machine, if that's what happened)

I'm in the process of writing a replacement for the mnesia backend, its failure/network segmentation recovery isn't what I'd like it to be. For instance, if there's a network segmentation for any real length of time, mnesia will detect that the two datasets have diverged and force you to choose which side is the authoritative truth. That's a lot more mess and user intervention than I'd like. :)
