### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by koudelka** [koudelka/honeydew#23]
- more examples
  - local mnesia queue
  - dead letter queue
  - failure mode chains (retry x times then move to dead letter, etc)
- user-facing api (the tl;dr section at the top of the README)
- mnesia + distillery caveat (need to stop mnesia before create_schema, but releases start all apps)
- move README to a wiki instead

**Comment by zacksiri** [comment]
I'm running into an issue with using HoneyDew with Distillery, any workaround?

**Comment by koudelka** [comment]
@zacksiri please open a new issue and provide more details about the issue you're having.
