### ISSUE TITLE
If ":finally" failure mode configured incorrectly then "FailureMode.Retry" will retry forever

### ISSUE THREAD

**Issue by dkataskin** [koudelka/honeydew#31]
In my case `:finally` had invalid configuration: `finally: Honeydew.FailureMode.Move` and this led to an interesting behaviour when honeydew tried to retry job forever. I had log entries like this:
`..retrying 0 more times, job: %Honeydew.Job{...}`
and then
`..retrying -1 more times, job: %Honeydew.Job{...}`
`..retrying -2 more times, job: %Honeydew.Job{...}`
and so on.

**Comment by koudelka** [comment]
hey @dkataskin, thanks for the bug report.

try out version `1.0.4`, it'll validate failure mode arguments to prevent that from happening again.

let me know how it works for you. :)
