### ISSUE TITLE
Postgres Support

### ISSUE THREAD

**Issue by jeremyjh** [koudelka/honeydew#48]
edit: All below was laboring under the misapprehension that this project already supported Postgres, which it doesn't. I'm working on a PR to add that side-by-side with Cockroach, and make it easier to add support and tests for other databases with an adapter model. Ideally the postgres adapter would just be ANSI SQL but I'm not sure reserve can be implemented with the same semantics without using CTEs, which is how I presently have it working.

`honeydew_fields` seems to be generating invalid SQL. In the example project I get a postgres syntax error when I run `ecto.migrate.` I'm using postgres 10.3 but none of this has changed recently so I'm a bit mystified how you didn't have the same result.

The reason for the failure is because the syntax of extract is wrong, it [should be ](https://www.postgresql.org/docs/current/static/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT)`EXTRACT('milisecond' from NOW())`).  This is generated fragment:

`(EXTRACT('millisecond', (CAST('1994-03-26 04:20:00' AS TIMESTAMP))) + CAST((CAST('1994-03-26 04:20:00' AS TIMESTAMP)) AS
 INT) * 1000)`

I fixed that in the macro but then it complains that datetime cannot be cast to an int - the second part. I think maybe what you are after here with the cast is implemented in the `epoch` function. 

```shell
[] ~/repos/elixir/honeydew/examples/ecto_poll_queue <master> ✗ mix ecto.create
Compiling 6 files (.ex)
Generated ecto_poll_queue_example app
The database for EctoPollQueueExample.Repo has been created
[] ~/repos/elixir/honeydew/examples/ecto_poll_queue <master> ✗ mix ecto.migrate

17:53:01.570 [info]  == Running EctoPollQueueExample.Repo.Migrations.CreatePhotosAndUsers.change/0 forward

17:53:01.572 [info]  create table photos
** (Postgrex.Error) ERROR 42601 (syntax_error): syntax error at or near ","
    (ecto) lib/ecto/adapters/sql.ex:200: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:96: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:96: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:104: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:102: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
```

**Comment by jeremyjh** [comment]
I guess your tests are using cockroachdb, is why they passed?  Cockroach is only compatible at the protocol level, it is not source or feature compatible with postgres. For some reason in the case of extract function they chose not to even be compatible with ANSI SQL.

**Comment by koudelka** [comment]
just pushed proper postgres support in https://github.com/koudelka/honeydew/commit/8134472246711d7bc3f5704620ddca14e4788f09 on master, try it out and let me know how it goes. :)

**Comment by jeremyjh** [comment]
@koudelka It works, thanks! Glad to have this in the main repository already.

I have a couple of suggestions based on the path I was headed down. 

The SQL in your `Postgres` module looks like pure ANSI, no special Postgres features. I'd call the module "ANSI". I'd also suggest changing the option you pass to `honeydew_fields` as `dialect` rather than `database`. Dialects now would be `:cockroach` and `:ansi`, in the future maybe someone will add `:cql` for Cassandra etc.

Second, you could have a single example project support multiple database adapters and run the test suite on both of them by using a separate MIX_ENV. I had started to make a separate MIX_ENV=pg_test, which changed the adapter - you could also use it in the migration to select the database/dialect depending on the value of `Mix.env`. I didn't get that far since you mentioned you were working on this, but the first step of the mix.config I did here: https://github.com/smartmetals/honeydew/commit/e0edef042dfe4b951c592ba72387cd2c87cd6609

If you take both these suggestions adding support for Maria is completely trivial I think, it would just be another MIX_ENV for test and I don't think would require any different SQL code but I didn't try it yet.

**Comment by koudelka** [comment]
Can you see a reason to want to select which dialect is used, outside of needing to manually select it when the adapter is ambiguous?

Thanks for the `MIX_ENV` idea! I really didn't like the idea of duplicating example project. :)

**Comment by jeremyjh** [comment]
@koudelka No, I think if the macros can get access to the applications' Repo configuration you could save the user the trouble, but I think also if a single ANSI dialect will cover Postgres and MySQL (as written it would work with SQL Server and Oracle too, I think) you can just default to that, which will cover 95% of users.

**Comment by koudelka** [comment]
combined the example into a single project, thanks again for the suggestion. :)
