### ISSUE TITLE
Honeydew hangs app startup 100ms per worker

### ISSUE THREAD

**Issue by aaronjensen** [koudelka/honeydew#5]
While diagnosing a slow `mix test` run, I came across the fact that our app startup was slow because we have two honeydew supervisors with a total of 15 or so workers. 

It seems that honeydew waits for 100ms for each worker during `init` which, in our case, slows down app startup time (and therefore every test run) by at least 1.5 seconds.

The offending line is here: 

https://github.com/koudelka/honeydew/blob/0fe01a1f516b8e1f6888dddf28ec5b9fb06a300a/lib/honeydew/worker.ex#L25

Relevant log from #elixir-lang:

```
3:04 PM A<aaronjensen> Aaron Jensen 
adding a 100ms sleep * # of workers during init seems like a bad idea, yea josevalim? :/
3:11 PM A<aaronjensen> Aaron Jensen 
is there a good way to defer starting of those before we are able to help fix honeydew?
3:16 PM J<josevalim> José Valim 
aaronjensen: yes, that sounds like a bad idea
3:17 PM J<josevalim> José Valim 
that's going to block the supervisor also starting it for 100ms
3:17 PM it is really really bad :(
3:17 PM benwilson512: are you using the lib above?
3:18 PM J<josevalim> José Valim 
aaronjensen:  ping the author, they should totally not do that
```

**Comment by koudelka** [comment]
Hey @aaronjensen,

Uhoh, busted by the big guy eh? :)

I initially wrote Honeydew for a fairly specific use-case. My workers were spawning linked processes that could crash pretty fast in certain cases, and I didn't want them taking jobs and then immediately returning them to the queue when they crash.

I'll move that behavior to my project's worker module, try out `0.0.11` and let me know how it goes.

**Comment by aaronjensen** [comment]
Thanks @koudelka. And hah, I thought about that after I pasted it... I'm not a rat, I swear 😄

Thanks for the quick fix, we'll give it a shot.

**Comment by aaronjensen** [comment]
btw, looks like this is still pending a mix publish

**Comment by koudelka** [comment]
All set.
