### ISSUE TITLE
Testing strategies 

### ISSUE THREAD

**Issue by yanshiyason** [koudelka/honeydew#52]
Hi there, thank you so much for the great library! Having a great time so far!

I am trying to write a unit test for a module which inserts jobs in a queue with `Honeydew.asyc` but my test case is asserting synchronously before the jobs are inserted.

Do you have any pointers on how one can assert jobs have been inserted?

**Comment by koudelka** [comment]
Hey hey, thanks :)

So the Queue process itself doesn't emit any events when it receives a job, so I believe you're really left with two options:

- Sleep and then ask the queue for a list of jobs.
```elixir
test "queue receives a job" do
  Honeydew.suspend(:my_queue)

  task = {:run, [1, 2, 3]}
  task |> Honeydew.async(:my_queue)
  Process.sleep(100) # could be tweaked
  Honeydew.filter(:my_queue, &match?(%Honeydew.Job{task: ^task}, &1))
end
```
- Enqueue a job that sends your test process a message, and `assert_receive`
```elixir
test "queue receives a job" do
  me = self()
  fn -> send (me, :hi) end |> Honeydew.async(:my_queue)
  assert_receive :hi
end
```

I imagine the former is what you're looking for, as the latter is more of a test of Honeydew itself.

Hope that helps!

**Comment by yanshiyason** [comment]
Thank you so much for taking the time to answer!
Your answer helped me discover another pattern I could use.

I might have wrote this in a way which is hard do unit test...
I rewrote my app logic as a weather app just for illustration.

I have a `Weather.Server` which is the public interface to the system and a `Weather.Worker`.
I want to test that when I call the following, a first job will be inserted, then a few more jobs will be inserted by afterwards.

```elixir
Weather.Server.get_weather(city: "Tokyo")
```

The server:

```elixir
defmodule Weather.Server do
  use GenServer

  @queue :weather_queue
  @name :weather_server

  ## Client API
  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, :ok, [name: @name])
  end

  def get_weather(city: city) do
    GenServer.call(@name, {:get_weather, city: city}, @timeout)
  end

  ## Server API
  def init(:ok) do
    {:ok, nil}
  end

  def handle_call({:get_weather, city: city}, _from, _state) do
    {:get_weather, [[city: city]]} |> Honeydew.async(@queue) # this enqueues the 1st job.
    {:reply, :ok, _state}
  end
end
```

The worker:

```elixir
defmodule Weather.Worker do
  @api_client Application.get_env(:weather, :api_client)
  @queue :weather_queue
  @behaviour Honeydew.Worker

  # Client
  def get_weather(city: city) do
    case @api_client.get_weather(city: city) do
      {:ok, weather: weather} ->
        weather.time_ranges
          |> Enum.each(&enqueue_job(city: city, time_range: &1)) # this will add n more jobs

        {:reply, :ok, :ok}
    end
  end

  def get_weather(city: city, time_range: time_range) do
    # ... more code here
  end

  # Private
  defp enqueue_job(args) do
    {:get_weather, [args]} |> Honeydew.async(@queue)
  end
end
```

The way I started fixing this, was to change the `enqueue_job` method in the worker, to send a message back to the server, and do the actual enqueuing there.

```elixir
defp enqueue_job(args) do
  Weather.Server.get_weather(args)
end
```

then add the code to handle that in the server:
```elixir
def get_weather(city: city, time_range: time_range) do
  GenServer.call(@name, {:get_weather, city: city, time_range: time_range}, @timeout)
end

def handle_call({:get_weather, city: city, time_range: time_range}, _from, _state) do
  {:get_weather, [[city: city, time_range: time_range]]} |> Honeydew.async(@queue)
  {:reply, :ok, _state}
end
```

Then I could somehow keep track of the which jobs have been queued in the server
by keing the hash with the task itself for example.
```elixir
def handle_call({:get_weather, city: city, time_range: time_range}, _from, state) do
  job = {:get_weather, [[city: city, time_range: time_range]]} |> Honeydew.async(@queue)

  new_state = Map.put(state, job.task, job)
  {:reply, :ok, new_state}
end
```

Then I could assert that the server's state includes the tasks in my tests...

Do you see a better way of doing things?

**Comment by koudelka** [comment]
Personally, I'm not a fan of making code and runtime processes more complex just to satisfy tests.

So instead of making those modifications, maybe consider making your queue names configurable in the application environment, just like how you're doing with the api client. In production and development, they'd have the same value. But in test, they'd be different.

Then, in your tests, you could start two queues, one for your initial `get_weather` calls, and the second for the calls that have a time range. The second queue would be suspended, or not have any workers running. You'd let the first job run (after checking that it'd been enqueued properly), then you'd check the second queue and assert that the time range jobs are present.

Alternatively, you could scrap all of the micro-manage-y tests and just run the whole thing as a big integration test, and have your `@api_client` send back messages to the testing process when it's told to `get_weather/1`. :)

**Comment by yanshiyason** [comment]
@koudelka Thank you so much for the advice! It helps tremendously. I will take your advice and come up with something!
