### ISSUE TITLE
[Feature] Ecto Queue - custom "delayed" job

### ISSUE THREAD

**Issue by wohlben** [koudelka/honeydew#76]
Hey,

I'm just starting my journey in elixir and started my first toy project last weekend.

In this project, I got a typical situation of an asynchronous task. There is just one tiny caveat... 
The database object gets created and a rate limited worker supplements the object with additional data. 
Now, with this new data I can finally start my new gloriously expensive task which takes all of 100ms to finish. 

any chance i could convince you to add custom constraints to the ecto queue like saying ? `some_field IS NOT NULL` when i'm spawning the workers?

I think the only change necessary would be in the `reserve` function, but I might be mistaken - I'm a total beginner after all ;)
https://github.com/koudelka/honeydew/blob/ebbb24396e6fa2ceb6d15633fe1f491e0bba62d9/lib/honeydew/sources/ecto/sql/postgres.ex#L43

I love the API btw :+1:

**Comment by wohlben** [comment]
i meant something basically like this... but i know i'm repeating myself: total beginner here 

```
    def reserve(state) do
      "UPDATE #{state.table}
      SET #{state.lock_field} = #{reserve_at(state)}
      WHERE id = (
        SELECT id
        FROM #{state.table}
        WHERE #{state.lock_field} BETWEEN 0 AND #{ready()} #{custom_clause()}
        ORDER BY #{state.lock_field}, #{state.key_field}
        LIMIT 1
        FOR UPDATE SKIP LOCKED
      )
      RETURNING #{state.key_field}, #{state.private_field}"
    end
    
    def custom_clause() do
      case Keyword.fetch!(args, :custom_clause) do
        nil -> ""
        clause -> clause
      end
    end

```

but if you think that it's not really worth supporting such a use-case, feel free to close this issue. I'm not sure how many people would use something like that  ;)

**Comment by koudelka** [comment]
@wohlben hey! i love the idea.

It's implemented and released under version 1.4.1 

https://github.com/koudelka/honeydew/tree/master/examples/ecto_poll_queue#execution-criteria

give it a spin and let me know how it goes. :)

**Comment by wohlben** [comment]
fantastic - thanks for that! 

just removed my workaround and it just works 👍

**Comment by koudelka** [comment]
🙇
