### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by WernerBuchert** [koudelka/honeydew#77]
Hi,
it's really strange, but at home the example works, but at work it doesn't work.
I'm using honeydew 1.4.1, my example is below, if i call start and then work,
i receive a list of jobs, but the jobs aren't really called.

defmodule MyWorker do
  def do_a_thing(test) do
    IO.puts("doing a thing#{test}!")
  end

  def start do
    :ok = Honeydew.start_queue(:my_queue, queue: {Honeydew.Queue.ErlangQueue, []})
    :ok = Honeydew.start_workers(:my_queue, MyWorker)
  end

  def test do
    {:do_a_thing, ["Test2"]} |> Honeydew.async(:my_queue)
  end

  def work do
    for i <- 1..10000 do
      {:do_a_thing, [Integer.to_string(i)]} |> Honeydew.async(:my_queue)
      :ok
    end
  end
end

The jobs are like this:

 %Honeydew.Job{
    by: nil,
    completed_at: nil,
    delay_secs: 0,
    enqueued_at: 1559028347918,
    failure_private: nil,
    from: nil,
    job_monitor: nil,
    private: -576460752303423068,
    queue: :my_queue,
    result: nil,
    started_at: nil,
    task: {:do_a_thing, ["1"]}
  },

I don't know why it works at home and not at work. 
At work, I'm using Windows with this version: Elixir 1.8.0 and OTP 20.2
At home, I'm using Ubuntu and Elixir 1.8.2 and OTP 22.0.1.
It's really strange, it's a fresh elixir project without other dependencies,
only {:honeydew, "~> 1.4.1"}.

Thanks,
Werner.

**Comment by koudelka** [comment]
Hi Werner,

I'm afraid I don't have any experience running Elixir on Windows. Perhaps try 1.82/22.0.1 on your Windows machine and see if it's still broken?

**Comment by danj3** [comment]
I have Elixir 1.8.2 running on OTP 20 and the simplest test doesn't work. After upgrading to OTP 22.0.2 it works properly.
