### ISSUE TITLE
Ecto.Adapters.MyXQL, isn't currently supported

### ISSUE THREAD

**Issue by basbz** [koudelka/honeydew#92]
Hi, I found Honeydew while looking for a solution for background processing  in a Phoenix app with use of Ecto. I followed the example and ran into the following issue:

```
 your repo's ecto adapter, Ecto.Adapters.MyXQL, isn't currently supported, but it's probably not hard to implement, open an issue and we'll chat! 
```

I had a look at the PG.Adapter, seems possible to implement it for MySQL. Any pointers on what I should look out for, did anybody already try and fail?

**Comment by koudelka** [comment]
Hey there @basbz!

Nobody (that I know of) has written a MyXQL module for Honeydew yet, but it should be fairly straight forward.

My only pointer would be to make sure that the "reserve" query is as efficient as possible while retaining atomic semantics. In the postgres adaptor, it uses `SKIP LOCKED` to prevent contention between multiple reserving processes.

Definitely drop me a line if you run into any snags, I'm happy to install mysql and lend a hand. :)

**Comment by basbz** [comment]
Hi, thanks for getting back to me 👍 
I'll take a look and hopefully get back with a PR.
closing the issue for now...
Best!
