### ISSUE TITLE
Final failure callback on worker?

### ISSUE THREAD

**Issue by messutied** [koudelka/honeydew#93]
Hi,

I'd like to know if there is a way to be notified and take an action upon a job failing after all retries, for example I'd like to retry the job many times and if it fails every time at the end send an email notifying about the failure, I don't seem to find an example that accomplishes this, I'd have to perhaps write my own `FailureMode` implementation?

Thanks.

**Comment by koudelka** [comment]
Hey @messutied!

Have you seen the `:finally` option provided by the `Retry` failure mode?

https://hexdocs.pm/honeydew/Honeydew.FailureMode.Retry.html

You'll have to write an `Email` failure mode, but that shouldn't be too bad.

Don't forget to tell the queue to do something with the job once you've sent the email, too. If you'd like to abandon the job, you can just call:

`Honeydew.FailureMode.Abandon.handle_failure(job, reason, [])`

**Comment by messutied** [comment]
Thanks for the quick reply @koudelka, yeah totally makes sense using the `:finally` option :) I was thinking on writing my own Retry mode, this is easier.
